export const twPaddings: Record<string, React.CSSProperties> = {

   'pt-0': { paddingTop: '0px' },
   'pb-0': { paddingBottom: '0px' },
   'pl-0': { paddingLeft: '0px' },
   'pr-0': { paddingRight: '0px' },
   'px-0': { paddingLeft: '0px', paddingRight: '0px'  },
   'py-0': { paddingTop: '0px', paddingBottom: '0px' },
   'p-0': { padding: '0px' },

   'pt-0.5': { paddingTop: '2px' },
   'pb-0.5': { paddingBottom: '2px' },
   'pl-0.5': { paddingLeft: '2px' },
   'pr-0.5': { paddingRight: '2px' },
   'px-0.5': { paddingLeft: '2px', paddingRight: '2px'  },
   'py-0.5': { paddingTop: '2px', paddingBottom: '2px' },
   'p-0.5': { padding: '2px' },

   'pt-1': { paddingTop: '4px' },
   'pb-1': { paddingBottom: '4px' },
   'pl-1': { paddingLeft: '4px' },
   'pr-1': { paddingRight: '4px' },
   'px-1': { paddingLeft: '4px', paddingRight: '4px'  },
   'py-1': { paddingTop: '4px', paddingBottom: '4px' },
   'p-1': { padding: '4px' },

   'pt-1.5': { paddingTop: '6px' },
   'pb-1.5': { paddingBottom: '6px' },
   'pl-1.5': { paddingLeft: '6px' },
   'pr-1.5': { paddingRight: '6px' },
   'px-1.5': { paddingLeft: '6px', paddingRight: '6px'  },
   'py-1.5': { paddingTop: '6px', paddingBottom: '6px' },
   'p-1.5': { padding: '6px' },

   'pt-2': { paddingTop: '8px' },
   'pb-2': { paddingBottom: '8px' },
   'pl-2': { paddingLeft: '8px' },
   'pr-2': { paddingRight: '8px' },
   'px-2': { paddingLeft: '8px', paddingRight: '8px'  },
   'py-2': { paddingTop: '8px', paddingBottom: '8px' },
   'p-2': { padding: '8px' },

   'pt-2.5': { paddingTop: '10px' },
   'pb-2.5': { paddingBottom: '10px' },
   'pl-2.5': { paddingLeft: '10px' },
   'pr-2.5': { paddingRight: '10px' },
   'px-2.5': { paddingLeft: '10px', paddingRight: '10px'  },
   'py-2.5': { paddingTop: '10px', paddingBottom: '10px' },
   'p-2.5': { padding: '10px' },

   'pt-3': { paddingTop: '12px' },
   'pb-3': { paddingBottom: '12px' },
   'pl-3': { paddingLeft: '12px' },
   'pr-3': { paddingRight: '12px' },
   'px-3': { paddingLeft: '12px', paddingRight: '12px'  },
   'py-3': { paddingTop: '12px', paddingBottom: '12px' },
   'p-3': { padding: '12px' },

   'pt-3.5': { paddingTop: '14px' },
   'pb-3.5': { paddingBottom: '14px' },
   'pl-3.5': { paddingLeft: '14px' },
   'pr-3.5': { paddingRight: '14px' },
   'px-3.5': { paddingLeft: '14px', paddingRight: '14px'  },
   'py-3.5': { paddingTop: '14px', paddingBottom: '14px' },
   'p-3.5': { padding: '14px' },

   'pt-4': { paddingTop: '16px' },
   'pb-4': { paddingBottom: '16px' },
   'pl-4': { paddingLeft: '16px' },
   'pr-4': { paddingRight: '16px' },
   'px-4': { paddingLeft: '16px', paddingRight: '16px'  },
   'py-4': { paddingTop: '16px', paddingBottom: '16px' },
   'p-4': { padding: '16px' },

   'pt-5': { paddingTop: '20px' },
   'pb-5': { paddingBottom: '20px' },
   'pl-5': { paddingLeft: '20px' },
   'pr-5': { paddingRight: '20px' },
   'px-5': { paddingLeft: '20px', paddingRight: '20px'  },
   'py-5': { paddingTop: '20px', paddingBottom: '20px' },
   'p-5': { padding: '20px' },

   'pt-6': { paddingTop: '24px' },
   'pb-6': { paddingBottom: '24px' },
   'pl-6': { paddingLeft: '24px' },
   'pr-6': { paddingRight: '24px' },
   'px-6': { paddingLeft: '24px', paddingRight: '24px'  },
   'py-6': { paddingTop: '24px', paddingBottom: '24px' },
   'p-6': { padding: '24px' },

   'pt-7': { paddingTop: '28px' },
   'pb-7': { paddingBottom: '28px' },
   'pl-7': { paddingLeft: '28px' },
   'pr-7': { paddingRight: '28px' },
   'px-7': { paddingLeft: '28px', paddingRight: '28px'  },
   'py-7': { paddingTop: '28px', paddingBottom: '28px' },
   'p-7': { padding: '28px' },

   'pt-8': { paddingTop: '32px' },
   'pb-8': { paddingBottom: '32px' },
   'pl-8': { paddingLeft: '32px' },
   'pr-8': { paddingRight: '32px' },
   'px-8': { paddingLeft: '32px', paddingRight: '32px'  },
   'py-8': { paddingTop: '32px', paddingBottom: '32px' },
   'p-8': { padding: '32px' },

   'pt-9': { paddingTop: '36px' },
   'pb-9': { paddingBottom: '36px' },
   'pl-9': { paddingLeft: '36px' },
   'pr-9': { paddingRight: '36px' },
   'px-9': { paddingLeft: '36px', paddingRight: '36px'  },
   'py-9': { paddingTop: '36px', paddingBottom: '36px' },
   'p-9': { padding: '36px' },

   'pt-10': { paddingTop: '40px' },
   'pb-10': { paddingBottom: '40px' },
   'pl-10': { paddingLeft: '40px' },
   'pr-10': { paddingRight: '40px' },
   'px-10': { paddingLeft: '40px', paddingRight: '40px'  },
   'py-10': { paddingTop: '40px', paddingBottom: '40px' },
   'p-10': { padding: '40px' },

   'pt-11': { paddingTop: '44px' },
   'pb-11': { paddingBottom: '44px' },
   'pl-11': { paddingLeft: '44px' },
   'pr-11': { paddingRight: '44px' },
   'px-11': { paddingLeft: '44px', paddingRight: '44px'  },
   'py-11': { paddingTop: '44px', paddingBottom: '44px' },
   'p-11': { padding: '44px' },

   'pt-12': { paddingTop: '48px' },
   'pb-12': { paddingBottom: '48px' },
   'pl-12': { paddingLeft: '48px' },
   'pr-12': { paddingRight: '48px' },
   'px-12': { paddingLeft: '48px', paddingRight: '48px'  },
   'py-12': { paddingTop: '48px', paddingBottom: '48px' },
   'p-12': { padding: '48px' },

   'pt-14': { paddingTop: '56px' },
   'pb-14': { paddingBottom: '56px' },
   'pl-14': { paddingLeft: '56px' },
   'pr-14': { paddingRight: '56px' },
   'px-14': { paddingLeft: '56px', paddingRight: '56px'  },
   'py-14': { paddingTop: '56px', paddingBottom: '56px' },
   'p-14': { padding: '56px' },

   'pt-16': { paddingTop: '64px' },
   'pb-16': { paddingBottom: '64px' },
   'pl-16': { paddingLeft: '64px' },
   'pr-16': { paddingRight: '64px' },
   'px-16': { paddingLeft: '64px', paddingRight: '64px'  },
   'py-16': { paddingTop: '64px', paddingBottom: '64px' },
   'p-16': { padding: '64px' },

   'pt-20': { paddingTop: '80px' },
   'pb-20': { paddingBottom: '80px' },
   'pl-20': { paddingLeft: '80px' },
   'pr-20': { paddingRight: '80px' },
   'px-20': { paddingLeft: '80px', paddingRight: '80px'  },
   'py-20': { paddingTop: '80px', paddingBottom: '80px' },
   'p-20': { padding: '80px' },

   'pt-24': { paddingTop: '96px' },
   'pb-24': { paddingBottom: '96px' },
   'pl-24': { paddingLeft: '96px' },
   'pr-24': { paddingRight: '96px' },
   'px-24': { paddingLeft: '96px', paddingRight: '96px'  },
   'py-24': { paddingTop: '96px', paddingBottom: '96px' },
   'p-24': { padding: '96px' },

   'pt-28': { paddingTop: '112px' },
   'pb-28': { paddingBottom: '112px' },
   'pl-28': { paddingLeft: '112px' },
   'pr-28': { paddingRight: '112px' },
   'px-28': { paddingLeft: '112px', paddingRight: '112px'  },
   'py-28': { paddingTop: '112px', paddingBottom: '112px' },
   'p-28': { padding: '112px' },

   'pt-32': { paddingTop: '128px' },
   'pb-32': { paddingBottom: '128px' },
   'pl-32': { paddingLeft: '128px' },
   'pr-32': { paddingRight: '128px' },
   'px-32': { paddingLeft: '128px', paddingRight: '128px'  },
   'py-32': { paddingTop: '128px', paddingBottom: '128px' },
   'p-32': { padding: '128px' },

   'pt-36': { paddingTop: '144px' },
   'pb-36': { paddingBottom: '144px' },
   'pl-36': { paddingLeft: '144px' },
   'pr-36': { paddingRight: '144px' },
   'px-36': { paddingLeft: '144px', paddingRight: '144px'  },
   'py-36': { paddingTop: '144px', paddingBottom: '144px' },
   'p-36': { padding: '144px' },

   'pt-40': { paddingTop: '160px' },
   'pb-40': { paddingBottom: '160px' },
   'pl-40': { paddingLeft: '160px' },
   'pr-40': { paddingRight: '160px' },
   'px-40': { paddingLeft: '160px', paddingRight: '160px'  },
   'py-40': { paddingTop: '160px', paddingBottom: '160px' },
   'p-40': { padding: '160px' },

   'pt-44': { paddingTop: '176px' },
   'pb-44': { paddingBottom: '176px' },
   'pl-44': { paddingLeft: '176px' },
   'pr-44': { paddingRight: '176px' },
   'px-44': { paddingLeft: '176px', paddingRight: '176px'  },
   'py-44': { paddingTop: '176px', paddingBottom: '176px' },
   'p-44': { padding: '176px' },

   'pt-48': { paddingTop: '192px' },
   'pb-48': { paddingBottom: '192px' },
   'pl-48': { paddingLeft: '192px' },
   'pr-48': { paddingRight: '192px' },
   'px-48': { paddingLeft: '192px', paddingRight: '192px'  },
   'py-48': { paddingTop: '192px', paddingBottom: '192px' },
   'p-48': { padding: '192px' },

   'pt-52': { paddingTop: '208px' },
   'pb-52': { paddingBottom: '208px' },
   'pl-52': { paddingLeft: '208px' },
   'pr-52': { paddingRight: '208px' },
   'px-52': { paddingLeft: '208px', paddingRight: '208px'  },
   'py-52': { paddingTop: '208px', paddingBottom: '208px' },
   'p-52': { padding: '208px' },

   'pt-56': { paddingTop: '224px' },
   'pb-56': { paddingBottom: '224px' },
   'pl-56': { paddingLeft: '224px' },
   'pr-56': { paddingRight: '224px' },
   'px-56': { paddingLeft: '224px', paddingRight: '224px'  },
   'py-56': { paddingTop: '224px', paddingBottom: '224px' },
   'p-56': { padding: '224px' },

   'pt-60': { paddingTop: '240px' },
   'pb-60': { paddingBottom: '240px' },
   'pl-60': { paddingLeft: '240px' },
   'pr-60': { paddingRight: '240px' },
   'px-60': { paddingLeft: '240px', paddingRight: '240px'  },
   'py-60': { paddingTop: '240px', paddingBottom: '240px' },
   'p-60': { padding: '240px' },

   'pt-64': { paddingTop: '256px' },
   'pb-64': { paddingBottom: '256px' },
   'pl-64': { paddingLeft: '256px' },
   'pr-64': { paddingRight: '256px' },
   'px-64': { paddingLeft: '256px', paddingRight: '256px'  },
   'py-64': { paddingTop: '256px', paddingBottom: '256px' },
   'p-64': { padding: '256px' },

   'pt-72': { paddingTop: '288px' },
   'pb-72': { paddingBottom: '288px' },
   'pl-72': { paddingLeft: '288px' },
   'pr-72': { paddingRight: '288px' },
   'px-72': { paddingLeft: '288px', paddingRight: '288px'  },
   'py-72': { paddingTop: '288px', paddingBottom: '288px' },
   'p-72': { padding: '288px' },

   'pt-80': { paddingTop: '320px' },
   'pb-80': { paddingBottom: '320px' },
   'pl-80': { paddingLeft: '320px' },
   'pr-80': { paddingRight: '320px' },
   'px-80': { paddingLeft: '320px', paddingRight: '320px'  },
   'py-80': { paddingTop: '320px', paddingBottom: '320px' },
   'p-80': { padding: '320px' },

   'pt-96': { paddingTop: '384px' },
   'pb-96': { paddingBottom: '384px' },
   'pl-96': { paddingLeft: '384px' },
   'pr-96': { paddingRight: '384px' },
   'px-96': { paddingLeft: '384px', paddingRight: '384px'  },
   'py-96': { paddingTop: '384px', paddingBottom: '384px' },
   'p-96': { padding: '384px' },

   'pt-SM': { paddingTop: '8px' },
   'pb-SM': { paddingBottom: '8px' },
   'pl-SM': { paddingLeft: '8px' },
   'pr-SM': { paddingRight: '8px' },
   'px-SM': { paddingLeft: '8px', paddingRight: '8px'  },
   'py-SM': { paddingTop: '8px', paddingBottom: '8px' },
   'p-SM': { padding: '8px' },

   'pt-MD': { paddingTop: '12px' },
   'pb-MD': { paddingBottom: '12px' },
   'pl-MD': { paddingLeft: '12px' },
   'pr-MD': { paddingRight: '12px' },
   'px-MD': { paddingLeft: '12px', paddingRight: '12px'  },
   'py-MD': { paddingTop: '12px', paddingBottom: '12px' },
   'p-MD': { padding: '12px' },

   'pt-LG': { paddingTop: '16px' },
   'pb-LG': { paddingBottom: '16px' },
   'pl-LG': { paddingLeft: '16px' },
   'pr-LG': { paddingRight: '16px' },
   'px-LG': { paddingLeft: '16px', paddingRight: '16px'  },
   'py-LG': { paddingTop: '16px', paddingBottom: '16px' },
   'p-LG': { padding: '16px' },

   'pt-XL': { paddingTop: '24px' },
   'pb-XL': { paddingBottom: '24px' },
   'pl-XL': { paddingLeft: '24px' },
   'pr-XL': { paddingRight: '24px' },
   'px-XL': { paddingLeft: '24px', paddingRight: '24px'  },
   'py-XL': { paddingTop: '24px', paddingBottom: '24px' },
   'p-XL': { padding: '24px' },

}

